### ISSUE TITLE
LibAprs on MEGA

### ISSUE THREAD

**Issue by peon5** [sh123/aprs_tracker#1]
Hi,
Thank you for sharing your nice project.
In a similar project I was trying to run the micromodem besides a Compass, Keypad and Display on an Arduino Nano. Unfortunately the little flash memory is filled slightly more than 100%.
Now I'm trying to run the LibAPRS on an Arduino MEGA. But I've no idea how to modify the code for different processors (e.g. redefine the Pins and maybe timings). How did you managed it? I couldn't find a LibAPRS for a MEGA 2560.
Best regards!

**Comment by sh123** [comment]
Hi, peon5. Thank you for having an interest. 

I haven't tried to run it on MEGA 2560, but I think that it has the same CPU as UNO, just more ports are added, more flash and RAM. So it should be "kind of" compatible, I think. In best case you should be able to run it wihout modifications. You just need to use the same LibAPRS pins and ports as on UNO.

If you need to redefine them then you need to look into the device.h file for ports and look for _BF macro in the code, which is used to toggle pins and modify those.

With UNO I spent quite some time to optimize the code to fit into the RAM. For example, I went through all libraries and decreased the size of the buffers (e.g. serial), decreased the size of buffers in LibAPRS itself, used fixed static buffers in aprs tracker sketchbook, tried to avoid deep calls to avoid much stack usage and so on... hope it helps.

**Comment by peon5** [comment]
Thank you for your reply!
Unfortunately the pin mapping on the arduino Mega is completely different and some necessary Pins for the modem are not accesable without changing the map. For now I just managed to change the RT/TX-Led. But I didn't made it to remap any other pins.
I found a comment on http://unsigned.io/microaprs-kiss-support/ where Mark Qvist postet: 
"... but as of now, there is no mapping for the pins and specific ADC and timer settings. If you can figure this out yourself, you can definitely run it on the 2560..." 
Obviously I cant figure it out ;)

**Comment by sh123** [comment]
I would look into AFSK_hw_init from AFSK.cpp, which initializes ADC and ISR routine below, which reads from ADC.

Also, found one table showing pin mapping between UNO and MEGA ports, which might help: https://docs.google.com/spreadsheets/d/16MIFE4ITEisEDUBh3H4A7WZga1Sm1Pm-igS3r0A58L8/pub?gid=0

**Comment by peon5** [comment]
Ok, you were right. Changing the input ports seems to be easy by manipulating the device.h. 
I followed your suggestions and changed the pins here (marked with "X"):
void AFSK_hw_init(void) {
    // Set up ADC
    AFSK_hw_refDetect();
    TCCR1A = 0;                                    
    TCCR1B = _BV(CS10) | _BV(WGM13) | _BV(WGM12);
    ICR1 = (((CPU_FREQ+FREQUENCY_CORRECTION)) / 9600) - 1;

    if (hw_5v_ref) {
        ADMUX = _BV(REFS0) | X; //Change ADC Pin here
    } else {
        ADMUX = X; ////Change ADC Pin here
    }

    ADC_DDR  &= ~_BV(X);  //Change ADC Pin here
    ADC_PORT &= ~_BV(X);  //Change ADC Pin here
    DIDR0 |= _BV(X);  //Change ADC Pin here
It's working so far. But changing the DAC looks more complicated. Because of the PTT-there are 5 output pins needed. In the LibAPRS libraries all of these pins are on port D. The Mega doesn't have one port with 5 usable pins including the needed pwm pins. That means it's necessary to move the PTT to an other port. 
I found a modified version of the similar MicroAPRS with changable pins. But it is not working:
https://github.com/markqvist/MicroAPRS/commit/a7a167c19ba03fcdf118c07345fa3656f09369ea#diff-b7827395262f4d9a4a93437b92eb27db

**Comment by sh123** [comment]
With DAC there is a need for 4 pins, so if you have 4 sequential pins free then you can use those and pick some PTT pin separately.

**Comment by peon5** [comment]
Sweet! Actually it's easier than I thought. It's not necessary to change the pins. I changed DAC port and DAC DDR to port A, LED port and DDR to port L and ADC Port and DDR to port F.
On the Mega it leads to fhe following pinout:
TX-pin 48,RX-pin 47,PTT-pin 25,DAC-pins26-29,ADC-pin A0. Somehow I was convinced  PWM pins were needed for DAC. Obviously I was wrong.
I'll try to proper change the pins later. But for now its working nice on the Mega and my project is back on.
Thanks a lot for your help sh123!

**Comment by sh123** [comment]
Nice to hear you managed to solve it, myself I kind of miscalculated RAM requirements for the tracker :), otherwise would go with mega instead of uno. Haven't realized that this nokia screen requires 500 bytes for RAM buffer, which is 1/4 of available RAM. Also, buffers eat quite a lot of RAM too. Mega, should be perfect as there should be enough RAM for small message history and no need to decrease buffer sizes and do other optimizations.

**Comment by Vitaliy86** [comment]
It can be done in only one output pin DAC? The remaining three are not used.

**Comment by Vitaliy86** [comment]
... As here https://github.com/f4goh/TNC/blob/master/TNC.cpp out on 5 pin afsk.

**Comment by w5nmr** [comment]
Hello, I try to bring aprs_tracker and bluetooth_tnc to run. A KISS.h is used, which unfortunately I can not find.
many thanks for the help !
translated by Google

**Comment by sh123** [comment]
@w5nmr, make sure all libraries from "Dependencies" section from README are installed. KISS.h comes from LibAPRS, which you need to install manually from https://github.com/sh123/LibAPRS/tree/aprs_tracker, it is in aprs_tracker branch.
